Repository Grey-Hat-07/Querification, pull requests merged in 2023-10, with the labels that each got.

#5 This is the solution of the 175th problem of the Leetcode SQL series
  175_LeetCOde_Sql_problem.sql
Labels: Hacktoberfest, HACKTOBERFEST-ACCEPTED

#8 1193. Monthly Transactions I - Leetcode SQL 50
  1193.monthlyTransactionsI.sql
Labels: HACKTOBERFEST-ACCEPTED

#10 Added feature file for 184_Leetcode_Department_highest_Salary
  184_Leetcode_Department_highest_Salary.sql
Labels: hacktoberfest-accepted

#12 [Feat]: Added file 620_Leetcode_Not_Boring_movies
  620_Leetcode_Not_Boring_movies.sql
Labels: hacktoberfest-accepted

#14 Feat: Added feature file 627_Leetcode_Swap_Salary
  627._Leetcode_Swap_Salary.sql
Labels: hacktoberfest-accepted

#15 Create 1633_Percentage_of_Users_Attended_a_Contest.sql
  1633_Percentage_of_Users_Attended_a_Contest.sql
  1978_Employees_Whose Manager_Left_the_Company.sql
Labels: hacktoberfest-accepted

#17 Added the solution of the 177th problem of sql of leetcode
  177_Nth_Highest_Salary.sql
Labels: hacktoberfest-accepted
